### ISSUE TITLE
Creating a FAQ page related to data entry

### ISSUE THREAD

**Issue by 1Vicky1** [International-Soil-Radiocarbon-Database/ISRaD#112]
Alison suggested it would be nice to have a FAQ page/guidelines for people entering data into templates. Is anyone working on this? 

I've listed some of the questions I've asked (and the answers I got from Alison) so far, not sure how frequent they are though: https://docs.google.com/document/d/1g35NllJo6y0GxYXSdCQfGu3YQ1NYrSueCzGYc6KMotc/edit?usp=sharing

**Comment by aahoyt** [comment]
Yes! We definitely want to do this. Thanks for the attachment - it's an excellent starting point. I will post the content on the website tomorrow. I already started a page for it, but didn't have enough content, so this will help.

We also discussed organizing this FAQ by "tab" and linking to helpful example templates for each tab.

Feel free to link to any template you found particularly helpful or other FAQ/common convention text here, and I will incorporate into the website.

**Comment by coreylawrence** [comment]
It looks like Grey and/or Alison got a start on this. I spent some time today cleaning it up and changing the organization somewhat. I also added links to "contribute" page so that this resource is now live. This will obviously be a work in progress. Please edit or submit additional questions/answers to be added here. 
https://international-soil-radiocarbon-database.github.io/ISRaD/template_faq/

**Comment by greymonroe** [comment]
Yep @aahoyt has made an awesome FAQ page https://international-soil-radiocarbon-database.github.io/ISRaD/template_faq/
