### ISSUE TITLE
geospatial data folder

### ISSUE THREAD

**Issue by greymonroe** [International-Soil-Radiocarbon-Database/ISRaD#115]
We need a central location for the geospatial data. It would be nice if we could host a link on our site

**Comment by coreylawrence** [comment]
This might be one of those circumstances were we don't want to serve up the actual data. It would be preferred if we could host scripts that would pull data from other managed repositories. That said, maybe we hold geospatial data behind the curtain so that it can be used during the build function to fill in select variables that are then included in israd_extra? I think there may be some permission issues if we download geospatial datasets and then serve them up again from our own links. Or am I miss understanding the issue?

**Comment by greymonroe** [comment]
That’s fine, we don’t need to share with everyone. We do need some central location for the data that we can use privately.

**Comment by jb388** [comment]
I like this plan, Shane. I say go for it.

**Comment by ShaneStoner** [comment]
Yeah, that makes sense. Perhaps we could include functions like this as an argument for the ISRaD.extra build function (unless I'm misunderstanding how ISRaD.extra works in R). The code is built in, but it doesn't do these functions by default.

Of course I don't know for sure, but I think as long as we document the source of the data and reference the ISRIC site/papers then it shouldn't be a big problem to serve up data derived from open-access spatial data. I will try to find out more.

**Comment by greymonroe** [comment]
issue has been fixed by using Keeper
