### ISSUE TITLE
Issues with Credits.md

### ISSUE THREAD

**Issue by aahoyt** [International-Soil-Radiocarbon-Database/ISRaD#117]
File on Github: ISRaD/ISRaD_data_files/database/credits.md 

It's great that this file is automatically compiled from the DOIs! However it still needs some fine-tuning, so as those things are noticed, list them here.

1) Some files are out of alphabetical order. Examples:
...Bol, Butman, He, Carbone....
....McClaran, De Tapia, McFarlane, Porras, Meyer....
This makes it much harder to find things. Not sure what is going on.

2) Some times studies come up as NULL (possible fix: If no valid DOI or ISRaD is entered, list the bibliographic reference field from the template metadata instead?)

3) Image prints in the middle of the list below <title>DOI Name 10.5194 Values</title>

**Comment by aahoyt** [comment]
@crlsierra @greymonroe meant to add you on this issue before.

Another weird thing- comparing the official "Credits" page which Carlos made awhile back with the auto-generated credits.md file (referenced above), some bibliographic entries get lost in the autogenerated one (although the files are still in the database). Examples: Agnelli (2002) and Hsieh (1996). 

Maybe this is a DOI issue? Were these files manually added to the website credits page? 

Ideally, we'd like to just have the Credits page of the website link to the credits.md file on Github, because that file is automatically generated every time new templates are added. It would be ideal to figure out why some studies are missing from the auto-generated credits.md file before doing this.

**Comment by crlsierra** [comment]
I just removed the dois that were manually excluded from the automated reference generation. It is possible that some dois may not show up because they were not correctly entered in the database. We need to check this next time the database is built.

Something I don't know is how the file ISRaD/ISRaD_data_files/database/credits.md makes its way to the gh-pages branch where it should be stored in the _pages folder. 
@greymonroe Do you have a way to copy this file from the master to the gh-pages branch? It'd be great if we can make this automatically so every time a new version of the database is build with new entries, the webpage gets automatically upgraded. However, I don't know how to copy files across branches.

**Comment by mguderle** [comment]
I checked the files, which delivered NULL in the credits.md - there were two files with a blank character in front of the first number of the DOI. After removing the blanks it works now. There is another study, which gives NULL - it's the PhD Thesis of Kate Heckman (Heckman_2010) because the link is not a DOI but it's a link (https://search.proquest.com/docview/815197522?pq-origsite=gscholar). It seems that rcrossref does not like these links.

The issue 3) Image prints in the middle of the list below <title>DOI Name 10.5194 Values</title> is also solved.

However, the order is still sometimes mixed up.

**Comment by jb388** [comment]
@mguderle The DOI should have been updated for Kate's thesis. I asked her to acquire a DOI from Zenodo, which she did. I can replace the version of that template with my copy, which has been expert reviewed and has the updated DOI.

**Comment by aahoyt** [comment]
Idea - Should we also read the "associated datasets" into the credits? For the case when the same data is in two papers. This would require people putting a DOI into the "associated datasets" field & also reading from that field in the function.

Unrelated - the issues with NULL and with some datasets out of alphabetical order are still present

**Comment by jb388** [comment]
Closing this issue as it seems to be a problem with the rcrossref fx and out of the scope of the ISRaD dev team.
