### ISSUE TITLE
pro_usda_soil_order not autofilling in "extra" file

### ISSUE THREAD

**Issue by Kate-Heckman** [International-Soil-Radiocarbon-Database/ISRaD#123]
Hi all,

Christina Schaedel and Craig Rasmussen put together a "fix" for autofilling the usda soil order. Would it be possible to apply that code when creating the "extra" files?

Many thanks,

Kate

**Comment by jb388** [comment]
Hi Kate, unfortunately that "fix" was static, and only worked for the database in the form it was in at the workshop in October. See issue #108.

**Comment by Kate-Heckman** [comment]
Ok. That’s unfortunate, but not that big of a deal. Thanks!

**Comment by coreylawrence** [comment]
I was just looking at this a little more closely. The original code that Christina prepared is pretty straightforward. It is just a “revalue” command that hardcodes a conversion of all existing pro_soil_taxon values to one of the soil orders. I searched the unique values for all the soil profiles and added in any missing values to the ISRaD.extra.fill_soilorders.R fucntion. 

While it is not included in the “Build” function, you should be able to call ISRaD.extra.fill_soilorders.R to convert values in profile$pro_soil_taxon to soil orders, which are printed in the profile$pro_usda_soil_order field, for any database you pass to that function At present it should work for anything currently showing up in the soil_taxon entry list.

**Comment by jb388** [comment]
Thanks for putting in the time to do that, Corey. However, the way the function is currently written it needs to be manually updated continually or else it will continue to fill non-standard values in the _pro_USDA_soil_order_ field if there isn't a matching revalue case (see issue #108 ).

Having the drop-down menu and controlled vocabulary for _pro_USDA_soil_order_ should help going forward, but it seems unrealistic to enforce it as "required" given that many papers only report soil taxonomy in WRB (older papers, of course, report in all sorts of other taxonomic systems or not at all). One partial solution is to have the Expert Reviewers request that the _pro_USDA_soil_order_ field is filled in.

Another solution could be to have a standard key for translating WRB to USDA (and vice-versa, I suppose)? If we create a specific _pro_WRB_soil_refgroup_ field in addition to _pro_USDA_soil_order_ and require at least one of them is filled in, it might be feasible. However, we'll still run into issues with papers that simply don't report these data.

**Comment by coreylawrence** [comment]
Yeah, just a band-aid on a band-aid. I still think we should make `pro_usda_soil_order` a soft-mandatory field, where it flagged as mandatory and comes up as a warning in the QA/QC but doesn't cause the template to fail. It is clear that there are a lot of entries in the soil_taxon that could easily be translated to soil_order. I'd be fine with including pro_WRB_soil_refgroup too but, in that case, do we also need pro_CND_soil_class? Either way, I think we need to try and push people to do this correctly otherwise, it is always going to be an issue where we are stepping through hundreds of individual miss-typed entries to translate by hand.

**Comment by Kate-Heckman** [comment]
As far as I know, there isn't a way to directly convert WRB to USDA, as I believe there is overlap and mixing among the orders. It will take someone with knowledge of soil morphology and pedogenesis to evaluate and translate among the two taxonomies. I think the expert reviewers will need to fill that role. If the expert reviewers don't feel comfortable with it, I suggest we ask Craig to be on call for the occasional taxonomic question.

**Comment by coreylawrence** [comment]
The question is: do we try and enforce some (semi)mandatory and _controlled_ soil order/reference group/classes in hopes that we can achieve greater homogeneity in soil classification or do we stick with the non-mandatory free for all that is soil_taxon? Either way there will be translation issues to fill the full datasets. 

With regards to that translation, I think it is better to script it (even though isn't always straightforward) so that there is a clear record of what was translated to what. If we rely on expert reviewers to make judgement calls on a case by case basis, the translation will be less consistent. That said, we could work with someone like Craig to right the USDA order to WRB reference to CND class translations.

**Comment by jb388** [comment]
I am hopeful that moving forward we can have the expert reviewers really push on folks to actually enter useful soil taxonomy data. To that end, I think it could be helpful to expand the list of taxonomy systems allowed in the pro_soil_taxon_sys field. Additions to the fill soil orders function could be built that recognize the pro_soil_taxon_sys and fill the pro_usda_soil_order field according to specific dictionaries keyed to each taxonomic system. 

In the meanwhile, something that will be useful immediately, no matter what we do in the future with regards to making fields mandatory or semi-mandatory, the "fill soil orders" function needs to be more dynamic. Instead of a simple revalue call, the function needs look for matches with known strings (which it does), but only fill the pro_USDA_soil_order field IF a recognized match is found. The issue now is that the function fills nonsense (the free text from the pro_soil_taxonomy field) when there isn't a match.

**Comment by Kate-Heckman** [comment]
Brilliant! I like it. Hopefully Craig won’t mind being volunteered.

**Comment by jb388** [comment]
I tweaked this function so it won't fill nonsense when there isn't a match in the revalue list. Still not a permanent or optimal fix, but now we can add it back into the package.
