### ISSUE TITLE
Idea: Remove data from R package

### ISSUE THREAD

**Issue by aahoyt** [International-Soil-Radiocarbon-Database/ISRaD#130]
This was discussed in detail at AGU. 

Possible idea: remove the data object itself from the R package. Data would be hosted on Github. Various options for the data include -the package could either have a function to call it, from the website, or the user could download the data object. Or the user could run the compile function on the list object, etc etc. 

Reasoning: the data is constantly being updated, and as a result, will require frequent CRAN package updates.  Ideally, this would reduce the frequency with which the package needs to be updated on CRAN, and frequency of the user needing to update their version of the package. It is more intuitive to download the latest data file than to have to update the package each time, which people may forget to do, and also takes awhile.
Additionally, no one will want to use the CRAN package if it doesn't have the latest data, they will always choose to download the dev branch.

**Comment by ktoddbrown** [comment]
I think that it's important to version the data object itself for reproducibility of studies/analysis. But otherwise would agree that separating the scripts and the data object makes a lot of sense. If you can't find other solutions ISCN may be able to mediate hosting with LBNL and mint DOIs for different versions. There are also a number of archives that would likely be happy to work with you to maintain versioning (EDI, ESS-DIVE, Pangeae come to mind).

**Comment by greymonroe** [comment]
The reasoning to remove the data object from the package makes sense to me.
We could add a function that downloads the data from the archive where we
chose to keep it. Lets disscuss in San Diego

**Comment by greymonroe** [comment]
discussed and created new issue with to do tasks
