### ISSUE TITLE
New ISRaD extra column - MRT

### ISSUE THREAD

**Issue by aahoyt** [International-Soil-Radiocarbon-Database/ISRaD#146]
Let's add mean residence time which is often reported in papers, but not currently included as it's a calculated value.

**Comment by greymonroe** [comment]
do we need another function for this?

**Comment by greymonroe** [comment]
@aahoyt I can add this if you give me the details and equation

**Comment by aahoyt** [comment]
Thanks! 
I'm not sure if we just want to add a column where people can type it in from the paper where it is already calculated, or if we want to do systematic calculations across the database. Some more thinking would be required for that.

**Comment by alkalifly** [comment]
It seems to me we have two independent questions to consider.

The first question is: Should we add a new column to enter mean residence times as reported in the original sources? This would have to be part of the master template, rather than part of ISRaD_extra. It could also be accompanied by an additional column for notes about the method the authors used to derive whatever value they reported (or this could just go into the layer/fraction notes column). To me, it seems the answer to this question is, "sure, why not?" because it is easy to implement, it doesn't affect anything else, and it allows for more original information to be retained.

The second question is: Should we add an ISRaD_extra function to derive mean residence times for all reported radiocarbon values? Of course, it would require making certain assumptions (i.e., choosing a model) to derive this value. Perhaps there could even be multiple derived values for multiple models/sets of assumptions. This "value added" data would be, ultimately, more useful than individual reported values, because all residence times would be consistent with each other. It would be a bit more complicated to implement compared to simply adding a new column, but would not really be that hard to implement. The only hard part would be selecting which models/assumptions to use.
