### ISSUE TITLE
Fractionation Classification Updates

### ISSUE THREAD

**Issue by coreylawrence** [International-Soil-Radiocarbon-Database/ISRaD#147]
See also #110 

I've spent some time working through a new framework for classifying fractionation methods, which I think will be more straightforward and accurate. I know this is a major change but I think this is something we need to do sooner than later. 

Please have a look at [THIS]( https://docs.google.com/spreadsheets/d/1EdWqRY--g71p36R-VwQHgJF8IS7kWPzpheuXe2EME9U/edit?usp=sharing) google drive file to see a comparison of the old vs. proposed new approach and add any suggestions you have as a comment

The new approach would require entries for frc_scheme, frc_approach, and frc_property to better capture the range of methods and to, hopefully, make it easier to standardize the categorization. The various combinations of approach and property choices are organized around the more general scheme selection.

After addressing any additional feedback on this, I will work on applying these changes to the database. My plan is to clone the repository, make the changes to the template, TIF, and existing data entries. Once it is working, we can merge the updates back with the main branch. However, if there is a better way, please let me know.

**Comment by 1Vicky1** [comment]
Dealing with fractionation in Doetterl et al. 2018, I am thinking how to classify their coarse POM (cPOM) which was separated after [Six et al. 2002 ](https://dl.sciencesocieties.org/publications/sssaj/abstracts/66/6/1981) by disrupting macroaggregate fraction (previously obtained by wet sieving >250 µm) in a microaggregate isolator (shaking with glass beads and wet sieving to get the >250 µm fraction). After disruption of maccroagregates, both cPOM and sand is captured on the 250 µm sieve, but sand content is then subtracted and C concentrations corrected so the data that I am entering describe cPOM only.

What description should I use? In the new version of fraction vocab proposed by Corey, there seems to be no suitable combination of descriptors.

I am considering **frc_incput** macroaggregates, **frc_scheme** Aggregate (or Particle size?), **frc_agent** wet sieve and **frc_property** occluded-light, frc_lower 250 and frc_upper 2000. However, I am not sure about the _occluded-light_ descriptor because technically the macroaggregate fraction can contain both occluded and free light fraction. Do we need a new "light" only or "POM" descriptor and add it to the Particle size or Aggregate frc_scheme?

**Comment by Kate-Heckman** [comment]
How do I enter water extractable carbon (the soluble fraction you can pull off in the lab -  not DOC from the field)? It doesn't work in the interstitial tab. I can put it in the fraction tab, which makes more sense, but there don't seem to be any good options for "f_property", "f_scheme_units", "frc_lower", or "frc_upper". Guidance?

**Comment by jb388** [comment]
@Kate-Heckman I'd put it in the fraction tab, too. It's hard to fit this procedure into our current scheme--there's no corresponding frc_property. However, my understanding is that the typical approach for chemical extractions is to use "presence/absence" for frc_scheme_units, and 0 and Inf as the upper and lower limits. Since frc_property isn't required, I guess I'd leave it blank, and put a note in the frc_note column that the water-extractable-fraction/residue was measured.

**Comment by Kate-Heckman** [comment]
Thanks, Jeff!
