### ISSUE TITLE
soil geo data files

### ISSUE THREAD

**Issue by greymonroe** [International-Soil-Radiocarbon-Database/ISRaD#169]
'USDA_taxon_key.csv': No such file or directory

add to Seafile

**Comment by greymonroe** [comment]
added 'USDA_taxon_key.csv' to the Seafile directory, but now when I run the QAQC its downloading some pretty large files (>3GB).

**Comment by jb388** [comment]
@greymonroe Hmm, I think your Seafile/Keeper must be out of synch somehow (or there's another issue). The Jena crew hasn't been running into issues, as far as I know. The the usda_taxon_key.csv file has been in the directory since Jan 12. 

The big files are the depth resolved organic carbon layers, ca. ~3 GB per file x 6 files.

**Comment by jb388** [comment]
Just to check---this is the pathname for the directory on my system: 

/Users/jeff/Seafile/ISRaD_keeper/ISRaD_extra_spatialdata/ISRaD_extra_soiltax

All the relevant files are within that directory.
