### ISSUE TITLE
Duplicate copies of data objects and files

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#194]
@greymonroe The build function creates duplicate copies of the ISRaD data objects and files: one set is in the directory "ISRaD_directory/ISRaD_data_files/database", the other set is in the directory inside that one, "ISRaD_data_files/database/ISRaD_database_files". 

Do we need to have both?

Edit: Is it because the files need to be written first and then zipped?

**Comment by greymonroe** [comment]
Good observation. I think they both exist for a reason. The ones in "ISRaD_Directory/ISRaD_data_files/database” don’t have the version extension, which is needed for functions that call those objects. Though I must admit I can’t remember where this is actually used. Can you think of anything? Im looking through scripts for cases where those are needed.

**Comment by jb388** [comment]
As far as I know, none of the scripts explicitly reference the version extension. If we do discover that the duplication is unnecessary, I would be in favor of keeping those with the version extension.

**Comment by greymonroe** [comment]
Right, none reference the ones with version number because that would be difficult to implement (you would have to update the code every time a new version was created), which is why I thought we had kept the ones without version in the name. In any case, I agree with you. If they are unnecessary we should just keep those in the ISRaD_database_files <https://github.com/International-Soil-Radiocarbon-Database/ISRaD/tree/master/ISRaD_data_files/database/ISRaD_database_files> folder with version names
