### ISSUE TITLE
Proposed additional template columns (non-required)

### ISSUE THREAD

**Issue by aahoyt** [International-Soil-Radiocarbon-Database/ISRaD#195]
Based on Gavin's work to ingest the synthesis compiled by Cristian Estop-Aragones as well as other papers with aquatic fluxes, we (Shane, Jeff, Gavin & Alison) propose some additional columns be added to the template to allow ISRaD to better accommodate this type of data.  Check out the attached file for details. 

All proposed variables are non-required, with the exception of two which default to blank, so should not affect any existing templates. If they are problematic, they can also be non-required.

The attached file includes the variables & their descriptions. Please feel free to make updates for clarity or suggest other names. Comments are welcome! I also included a few other updates which had been discussed in the past, but had not yet been implemented.

[ProposedTemplateUpdates_4Jul2019.xlsx](https://github.com/International-Soil-Radiocarbon-Database/ISRaD/files/3360051/ProposedTemplateUpdates_4Jul2019.xlsx)

We hope to make changes to the Estop-Aragones synthesis ingest using this template ASAP, so if you plan to comment but need additional time to do so, let us know. Thanks!

**Comment by jb388** [comment]
I went ahead and made these template changes. However, it's easily updated or undone if anyone has new input or concerns. 

I also successfully ran through the build process to make sure that nothing about the changes breaks what is already there.

Since I made a couple of (very minor) changes to the version of the document Alison linked above, I've attached the new file here:

[ProposedTemplateUpdates_4Jul2019.xlsx](https://github.com/International-Soil-Radiocarbon-Database/ISRaD/files/3362925/ProposedTemplateUpdates_4Jul2019.xlsx)

**Comment by aahoyt** [comment]
Thanks for the update! 

In the updated (current) master template, any time you type zero "0" in any of the fields, it doesn't show up in the cell. The cell looks blank. However, if you hover over it, the zero is still there. 
@jb388 Do you think this was introduced in the template updates?

Overall probably not a big deal, just kind of weird. But it's relevant for example, entering 0% deforested in the new pro_deforested field and could come up for other values. Other tabs seem to be ok.

**Comment by jb388** [comment]
Hmm, that is weird. I think it's just an excel formatting thing, though. Shouldn't actually impact anything, but we should keep an eye out for it. Gonna close this.
