### ISSUE TITLE
Include column(s) to better characterize sonication for fractionation studies

### ISSUE THREAD

**Issue by coreylawrence** [International-Soil-Radiocarbon-Database/ISRaD#199]
One reviewer of the ISRaD manuscript ([discussion here](https://www.earth-syst-sci-data-discuss.net/essd-2019-55/#discussion)) suggested including additional detail for sonication of samples for fractionation studies in the template/database. 

Addressing this issue would likely result in the addition to at least two or three new (non-required) columns to the fraction tab: (1) sonication energy, (2) frequency, (3) time. This issue is intended to facilitate discussion of this proposed addition, which can be implemented during revisions to the fractionation categorization scheme (see also #147). 

Would the addition of these new variables allow for capturing the pertinent information regarding sonication? Your input is appreciated.

**Comment by jb388** [comment]
The proposed variables seem adequate for characterizing sonication treatment. I would lean towards not modifying the template, mostly because this information would need to be (should be) obtained for the studies already entered in ISRaD. But I'm not against it per se. 

I would leave it to the discretion of whomever takes up the challenge of implementing the fraction table overhaul, i.e. as proposed in #147

**Comment by jb388** [comment]
Closing as fraction overhaul is complete
