### ISSUE TITLE
f_upper & f_lower not appropriate for some fraction schemes

### ISSUE THREAD

**Issue by aahoyt** [International-Soil-Radiocarbon-Database/ISRaD#20]
What should users fill in if fraction scheme results in presence/absence for the cutoff? This should be clarified somewhere since this is a required field.

Examples where this must come up:
frc_property: carbonate, carbonate-free, base soluble, base insoluble, acid soluble, acid insoluble, respired
frc_scheme: acid, base, chem_extraction, 

(related, we should probably remove "respired" as an option since that would now go on the incubation tab)

**Comment by aahoyt** [comment]
They should put 0 and 1 as lower and upper

**Comment by greymonroe** [comment]
do we need to add this documentation somewhere to explain to users?

**Comment by ShaneStoner** [comment]
Hey I'm going to try to boot up an old issue again.

I've entered a few papers (Goh 1976, 1977, Pessenda 1996) that have used acid-base-acid extraction to produce Humin, Humic Acid, and Fulvic Acid fractions. We talked about this during the September hackathon, but I wanted to confirm a methodology for entering these data that is consistent. I can then add something to the user documentation regarding this fractionation scheme. I used two different methods, let me know your thoughts on each and which is most appropriate.

Humins are not soluble in basic or acidic conditions, so it is the remaining fraction of organic carbon after acid or basic. It doesn't seem appropriate to classify it as acid- or base-insoluble, since both are true, so I have been treating this as presence/absence, with the frc_property as "ABA residual". In the Pessenda paper, we used ABA residual with cutoffs of 3 and 10. 

Humic acids are those organic compounds that are soluble in alkaline conditions but not in acidic conditions. I have used "acid insoluble" as frc_property, with pH units. The lower cutoff is 0, and the upper cutoff is 2. Following the Pessenda paper thinking, this would be acid-insoluble with cutoffs 0 to 3?

Fulvic acids are soluble at any pH, so I have been treating them as "acid soluble" (lower cutoff is 0, upper cutoff is 2). However, this may cause problems if frc_property isn't filtered. I'm not sure how this fits into the Pessenda way of thinking. Acid-soluble with cutoffs of 0-3, or base soluble with 3-14? Should we add another property that is "dissolved" or just "soluble"?

Should we change fulvic acids to "base soluble" and switch the cutoffs to 2 and 14? Should we keep it the way I have done it? Or do you have other ideas? Since this is an outdated technique, it isn't the most critical issue but I would like to provide information for future users on the standard protocol. 

I've attached Goh 1976 and 1977, let me know what you think.


[Goh_1977.xlsx](https://github.com/International-Soil-Radiocarbon-Database/ISRaD/files/2611107/Goh_1977.xlsx)


[Goh_1976.xlsx](https://github.com/International-Soil-Radiocarbon-Database/ISRaD/files/2611099/Goh_1976.xlsx)

**Comment by aahoyt** [comment]
This came up again today. Could we just add "humin", "humic_acid" and "fulvic acid" as controlled vocab under frc_property? I think this would help alleviate confusion.

Also I found this image helpful:
![fractionation of soil humic substances](https://user-images.githubusercontent.com/5949455/49260174-3fed8a00-f3f1-11e8-8cd4-82e39e7d814a.jpg)

**Comment by jb388** [comment]
vis #147
