### ISSUE TITLE
Generating credits from "associated_datasets" field

### ISSUE THREAD

**Issue by ShaneStoner** [International-Soil-Radiocarbon-Database/ISRaD#202]
While working with the Claire Treat synthesis, I found that several of the entries contain data from several publications, and these are currently populated into the "associated_datasets" on the metadata table. There is no designation in her tables as to from which publication the individual data originated.

When ISRaD is compiled, are publications/dois from the "associated_datasets" field being compiled into lists of credits, either as a report or to be listed on the ISRaD webpage? Have we had this discussion before? Hopefully this is an easy quick thing, if it isn't there already. Thanks. @crlsierra @jb388

**Comment by jb388** [comment]
I think the problem here is inconsistencies in the type of data entered in the "associated datasets" field, specifically that the suggested value to enter is of the type "firstAuthor_year"---which doesn't help us track down a DOI. We would need to manually go through each template with a value entered and replace whatever text is entered with an actual DOI. This shouldn't be too arduous, as the associated datasets field in most templates is blank. Adding code to include the associated datasets column in the credits.md file is trivial.

**Comment by jb388** [comment]
Update for posterity: for templates with two entries that share the same data (e.g. two published studies that each report the same data), the solution for giving credit and tracing the data to both studies is to enter the primary study (usually with the earlier publication date) in the metadata table of a template and reference that study in the subordinate tables, while adding the secondary study as a second record in the metadata table of the same template with a metadata_note explaining the linkage.
