### ISSUE TITLE
Error: lyr_graven_atm

### ISSUE THREAD

**Issue by mguderle** [International-Soil-Radiocarbon-Database/ISRaD#232]
While updating the ISRaD DB with the build function, the following error occurs:

Error in `$<-.data.frame`(`*tmp*`, "lyr_graven_atm", value = c(109.8,  : 
  replacement has 17448 rows, data has 17432

**Comment by jb388** [comment]
@mguderle So this issue only occurred when you were ingesting new entries, correct? Which entries were they?

**Comment by jb388** [comment]
Honestly I'm pretty stumped here. I can't manage to reproduce the issue on my own. But I'll give it another shot later today or tomorrow.

**Comment by jb388** [comment]
@mguderle 
FYI, I ran the "build" function with the two new entries (Nave_2017, McFarlane_2018) and pushed to git. Again, I am not getting this "lyr_graven_atm" issue, and I'm not sure why. 

Did you delete the old versions of the entries before running build? Since it's not happening for me, I wonder if it is a platform-based issue, since you run windows (right?) and I am running mac OS. 

I'll keep thinking about it...
