### ISSUE TITLE
Topics/questions for next ISRaD meeting

### ISSUE THREAD

**Issue by jb388** [International-Soil-Radiocarbon-Database/ISRaD#239]
Last week (1 July 2020) we had a good informational session explaining some of the core functions of ISRaD (QAQC, compile, ISRaD.build), and gave a primer on what happens to data once it has been successfully submitted, i.e. the technical steps behind ingesting new data and updating the database.

We'd like to revisit some of these same topics in a new meeting for those who weren't able to participate last week, as well as discuss other code-related or technical aspects of ISRaD. The meeting time is still to be determined, but I thought we could use this space to brainstorm possible topics for the next or other future ISRaD meetings. 

Please respond to this issue with questions and suggestions. What are your burning questions about ISRaD? (If you are unable to respond here on github, you can also submit questions or suggestions to info.israd[at]gmail.com)

**Comment by coreylawrence** [comment]
Thanks for getting this started Jeff. I think having another code related discussion to include a broader audience is a great idea. 

Separately, I would like to have a short discussion on the **July, 15th** of some questions that Sue Trumbore and I will be addressing with the National Academies Soil Information Systems Planning Committee. This discussion will inform a workshop that the National Academies group is planning, which is now scheduled for [January 2021](https://www.nationalacademies.org/our-work/exploring-a-dynamic-soil-information-system-a-workshop). I would like to get input on the topics (listed below) so that the ISRaD perspective is adequately represented. I think Sue and I have a good general perspective on these issues but it would be great to get some specific input that folks would like conveyed. Please have a look through these questions and make note of any points that you would like us to bring up in the meeting.

The questions they would like us to address are: 
·         What is your vision, and what do you want to do with soil data?
·         What is working well with your current database or data collecting effort?  
·         What are the roadblocks?
·         How is data curated, transferred, analyzed, and shared?
·         What are the drivers of change?
·         What do you want to be able to do?
·         How is your data being used? Who uses it?
·         What infrastructure is need to capture and store the data?
·         At what spatial and temporal scales are different variables measured?
