### ISSUE TITLE
False QAQC flag on mineralogy

### ISSUE THREAD

**Issue by Kate-Heckman** [International-Soil-Radiocarbon-Database/ISRaD#94]
Hi all,
You should be able to enter "+", "++" or "+++" in the mineralogy columns. The QAQC is flagging these entries.
fraction tab...
	WARNING non-numeric values in frc_quartz column
	WARNING non-numeric values in frc_alkali_feldspar column
	WARNING non-numeric values in frc_mica_chlorite column
	WARNING non-numeric values in frc_amphibole column
	WARNING non-numeric values in frc_kaol_halloy column
	WARNING non-numeric values in frc_smect_vermic column

**Comment by jb388** [comment]
The issue here is that we set the class of this field to numeric, so character values like "+" cause issues. Since Excel doesn't like it when you enter + without a leading quote, I thought a good solution would be to keep the column as numeric but reserve the values 101/102/103 for +/++/+++. I updated the template and template info file accordingly.
