### ISSUE TITLE
+/++/+++ in numeric columns, need to fix QAQC or master template file

### ISSUE THREAD

**Issue by greymonroe** [International-Soil-Radiocarbon-Database/ISRaD#96]
Sollins et al 2009 is failing QAQC because several columns which are defined as numeric in the info file contain non-numeric "+" or "++" which are qualitative values of the variables. According to the template file, these should accepted. Either the template file needs to be changed, and these values deleted from Sollins et al 2009, or the QAQC needs to be changed to allow for these values

**Comment by jb388** [comment]
I updated Sollins 2009 to match the conventions in the template info file, i.e. '+' = 101, '++' = 102, '+++" = 103.

The current work around seems problematic (i.e. assigning numeric values as qualitative proxies). At the Jena hackathon, the group seemed in favor of removing the option to enter qualitative data. Owing the to challenges of interpreting qualitative data across studies, we thought these data were of little relevance to ISRaD. Thoughts?

**Comment by 1Vicky1** [comment]
Intuitively, I would try to keep the qualitative data in the database despite the little interest in them at the moment, i.e. try not to lose information. I´m not that experienced in coding but couldn´t all the values be compiled as character vectors in the first step? Then a function, e.g. as part of ISRaD extra could filter out/convert only the quantitative values (i.e. those without "+" characters). In the future someone who´s interested could play with the data, write a function to convert qualitative data to quantitative or vice versa. But I guess that QAQC is part of the problem here too, right?

**Comment by jb388** [comment]
@1Vicky1 Rather than lose data (which I agree is not ideal), I implemented the numeric solution described above: i.e. using the values 101, 102, and 103 for "+", "++", and "+++", respectively. 

Does it seem difficult or problematic to stick with this approach? The thought was that values above 100 would be outside the range of %, so it would be relatively obvious that these values should be filtered out when using the quantitative data, or vice versa if people were interested in the qualitative values. This also allows us to screen values <0, >103, or non-numeric entries with the current QAQC tool.

**Comment by 1Vicky1** [comment]
I think the workaround is OK, i.e. better than losing the data - I thought for some reason this solution is problematic for you or the others so I was trying to think of another one! To me it seems fine - if it gets well explained in the Template info file.

**Comment by coreylawrence** [comment]
I can't think of a reason that this solution doesn't work. In other words, I think we have solved the issue but we can leave this open a bit longer just to be sure that everyone is happy

**Comment by greymonroe** [comment]
> I implemented the numeric solution described above: i.e. using the values 101, 102, and 103 for "+", "++", and "+++", respectively.

Is this explained anywhere in the manuscript or websites so users know what these values mean when they encounter them?

**Comment by jb388** [comment]
The convention is explained in the template info file.
